version: 2
enable-beta-ecosystems: true

updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"

    - package-ecosystem: "nuget"
      directory: "/DevSkim-DotNet/ManualGenerator"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "nuget"
      directory: "/DevSkim-DotNet/Microsoft.DevSkim.CLI"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "nuget"
      directory: "/DevSkim-DotNet/Microsoft.DevSkim.LanguageProtoInterop"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "nuget"
      directory: "/DevSkim-DotNet/Microsoft.DevSkim.LanguageServer"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "nuget"
      directory: "/DevSkim-DotNet/Microsoft.DevSkim.Tests"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "nuget"
      directory: "/DevSkim-DotNet/Microsoft.DevSkim.VisualStudio.SourceGenerator"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "nuget"
      directory: "/DevSkim-DotNet/Microsoft.DevSkim.VisualStudio"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "nuget"
      directory: "/DevSkim-DotNet/Microsoft.DevSkim"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/DevSkim-VSCode-Plugin/client"
      schedule:
          interval: "daily"
      versioning-strategy: increase

    - package-ecosystem: "npm"
      directory: "/DevSkim-VSCode-Plugin"
      schedule:
          interval: "daily"
      versioning-strategy: increase
